"""ONE-SHOT MIGRATION ONLY. Not a runtime compatibility path.

Convert local catalog v3.0 files to catalog v3.1. The migration fills only
deterministic structure, locator paths, title/provenance candidates, hashes, and
figure inventory. Semantic gaps are recorded in quality_control and should be
regenerated by the catalog curator before formal validation.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from config.settings import PAPER_RAW_DIR, PAPERS_DIR
from src.file_fingerprint import compute_file_hashes
from src.path_utils import normalize_repo_path
from src.services.ingest_ids import PAPER_NUMBER_RE
from src.services.v2_library import empty_catalog, now_iso, validate_catalog_schema
from src.utils.atomic_io import atomic_write_json


FIXTURE_PATTERNS = ("测试夹具", "test_fixture")


def _read_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _file_md5(path: Path) -> str:
    if not path.exists() or not path.is_file():
        return ""
    return str(compute_file_hashes(path).get("md5") or "")


def _marker_number(folder: Path) -> str:
    for marker in sorted(folder.glob("*.paper.number")):
        if marker.name.endswith(".paper.number"):
            return marker.name[: -len(".paper.number")]
    return ""


def _paper_number(folder: Path, old_catalog: dict[str, Any], metadata: dict[str, Any]) -> str:
    for value in (
        old_catalog.get("paper_number"),
        metadata.get("paper_number"),
        metadata.get("paper_raw_id"),
        _marker_number(folder),
        folder.name,
    ):
        text = str(value or "")
        if PAPER_NUMBER_RE.fullmatch(text):
            return text
    return ""


def _prefix(folder: Path, catalog_path: Path, metadata: dict[str, Any]) -> str:
    if catalog_path.name.endswith(".catalog.json"):
        return catalog_path.name[: -len(".catalog.json")]
    if metadata.get("paper_id"):
        return str(metadata["paper_id"])
    return folder.name


def _paper_id(folder: Path, old_catalog: dict[str, Any], metadata: dict[str, Any], prefix: str) -> str:
    for value in (
        old_catalog.get("paper_id"),
        metadata.get("paper_id"),
        "" if PAPER_NUMBER_RE.fullmatch(folder.name) else folder.name,
        "" if PAPER_NUMBER_RE.fullmatch(prefix) else prefix,
    ):
        text = str(value or "")
        if text:
            return text
    return ""


def _metadata_path(folder: Path, prefix: str) -> Path:
    exact = folder / f"{prefix}.metadata.json"
    if exact.exists():
        return exact
    candidates = sorted(folder.glob("*.metadata.json"))
    return candidates[0] if candidates else exact


def _catalog_paths(root: Path) -> list[Path]:
    if not root.exists():
        return []
    skip_parts = {"quarantine", "output", "__pycache__"}
    return [
        path
        for path in sorted(root.rglob("*.catalog.json"))
        if not any(part in skip_parts or part.startswith(".") for part in path.parts)
    ]


def _first_markdown_h1(md_path: Path) -> str:
    if not md_path.exists():
        return ""
    try:
        for line in md_path.read_text(encoding="utf-8", errors="ignore").splitlines()[:100]:
            text = line.strip()
            if text.startswith("# "):
                return text[2:].strip()
    except OSError:
        return ""
    return ""


def _title_original(metadata: dict[str, Any], md_path: Path, old_catalog: dict[str, Any]) -> tuple[str, str, list[str], list[str]]:
    warnings: list[str] = []
    title_obj = metadata.get("title") if isinstance(metadata.get("title"), dict) else {}
    metadata_title = str(title_obj.get("original") or "").strip()
    old_identity = old_catalog.get("content_identity") if isinstance(old_catalog.get("content_identity"), dict) else {}
    raw_candidates = old_identity.get("content_title_original_candidates")
    if not isinstance(raw_candidates, list):
        raw_candidates = []
    candidates: list[str] = []
    for item in raw_candidates:
        text = str(item or "").strip()
        if not text:
            continue
        if PAPER_NUMBER_RE.fullmatch(text):
            warnings.append("removed paper-number-like content_title_original_candidate")
            continue
        candidates.append(text)
    h1 = _first_markdown_h1(md_path)
    for source_name, value in (("metadata.title", metadata_title), ("markdown_h1", h1), ("v3.0_candidates", candidates[0] if candidates else "")):
        if value and not PAPER_NUMBER_RE.fullmatch(value):
            return value, source_name, candidates, warnings
    return "", "fallback", candidates, warnings


def _remove_fixture_text(value: Any, warnings: list[str]) -> Any:
    if isinstance(value, str):
        if any(pattern in value for pattern in FIXTURE_PATTERNS):
            warnings.append("removed fixture/test text from catalog")
            return ""
        return value
    if isinstance(value, list):
        return [_remove_fixture_text(item, warnings) for item in value]
    if isinstance(value, dict):
        return {key: _remove_fixture_text(item, warnings) for key, item in value.items()}
    return value


def _figure_inventory(folder: Path, md_path: Path) -> dict[str, Any]:
    refs: list[str] = []
    if md_path.exists():
        text = md_path.read_text(encoding="utf-8", errors="ignore")
        refs.extend(re.findall(r"!\[[^\]]*\]\((images/[^)]+)\)", text))
    image_files = []
    images_dir = folder / "images"
    if images_dir.is_dir():
        image_files = [f"images/{p.name}" for p in sorted(images_dir.iterdir()) if p.is_file()]
    seen = []
    for value in [*refs, *image_files]:
        if value not in seen:
            seen.append(value)
    if seen:
        return {
            "extraction_status": "extracted",
            "items": [{"label": "", "path": path, "caption": "", "source": "markdown_or_images_dir"} for path in seen],
        }
    if images_dir.is_dir():
        return {"extraction_status": "none_found", "items": []}
    return {"extraction_status": "not_scanned", "items": []}


def _copy_group(new: dict[str, Any], old: dict[str, Any], key: str, warnings: list[str]) -> None:
    if isinstance(old.get(key), dict) and isinstance(new.get(key), dict):
        cleaned = _remove_fixture_text(deepcopy(old[key]), warnings)
        for child_key, value in cleaned.items():
            if child_key in new[key]:
                new[key][child_key] = value


def _missing_fields(catalog: dict[str, Any]) -> list[str]:
    missing: list[str] = []
    identity = catalog.get("content_identity") or {}
    classification = catalog.get("classification") or {}
    writing = catalog.get("writing_value") or {}
    provenance = catalog.get("provenance") or {}
    if not identity.get("content_title_zh"):
        missing.append("content_identity.content_title_zh")
    if not identity.get("content_title_original"):
        missing.append("content_identity.content_title_original")
    if not classification.get("primary_domain"):
        missing.append("classification.primary_domain")
    if not catalog.get("terminology"):
        missing.append("terminology")
    if not writing.get("short_summary"):
        missing.append("writing_value.short_summary")
    for key in ("generated_at", "generator"):
        if not provenance.get(key):
            missing.append(f"provenance.{key}")
    return missing


def migrate_catalog(catalog_path: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    folder = catalog_path.parent
    old = _read_json(catalog_path)
    prefix = _prefix(folder, catalog_path, {})
    metadata_path = _metadata_path(folder, prefix)
    metadata = _read_json(metadata_path)
    prefix = _prefix(folder, catalog_path, metadata)
    paper_number = _paper_number(folder, old, metadata)
    paper_id = _paper_id(folder, old, metadata, prefix)
    md_path = folder / f"{prefix}.md"
    pdf_path = folder / f"{prefix}.pdf"
    asset_manifest_path = folder / f"{prefix}.asset_manifest.json"

    new = empty_catalog()
    warnings: list[str] = []
    new["library_locator"] = {
        "paper_number": paper_number,
        "paper_id": paper_id,
        "paper_dir": normalize_repo_path(folder),
        "asset_refs": {
            "markdown": md_path.name,
            "pdf": pdf_path.name,
            "metadata": metadata_path.name if metadata_path.exists() else f"{prefix}.metadata.json",
            "catalog": catalog_path.name,
            "asset_manifest": asset_manifest_path.name,
            "images_dir": "images/",
        },
    }

    old_identity = old.get("content_identity") if isinstance(old.get("content_identity"), dict) else {}
    title_original, title_source, candidates, title_warnings = _title_original(metadata, md_path, old)
    warnings.extend(title_warnings)
    new["content_identity"].update({
        "content_title_zh": str(old_identity.get("content_title_zh") or ""),
        "content_title_original": title_original,
        "content_title_original_source": title_source,
        "content_title_original_candidates": candidates,
        "content_language": str(old_identity.get("content_language") or metadata.get("language") or ""),
        "document_type": str(old_identity.get("document_type") or metadata.get("entry_type") or "article"),
        "title_quality": {
            "source": title_source,
            "confidence": 1.0 if title_source == "metadata.title" else 0.7 if title_original else 0.0,
            "warnings": title_warnings,
        },
    })

    for key in ("classification", "screening", "research_card", "evidence_profile", "provenance"):
        _copy_group(new, old, key, warnings)
    old_notes = old.get("content_notes") if isinstance(old.get("content_notes"), dict) else {}
    if old_notes:
        cleaned_notes = _remove_fixture_text(deepcopy(old_notes), warnings)
        for old_key, new_key in (
            ("short_summary", "short_summary"),
            ("long_summary", "long_summary"),
            ("possible_use_in_writing", "possible_use_in_writing"),
            ("open_questions", "open_questions"),
            ("warnings", "warnings"),
        ):
            if old_key in cleaned_notes:
                new["writing_value"][new_key] = cleaned_notes[old_key]
    if isinstance(old.get("terminology"), list):
        new["terminology"] = _remove_fixture_text(deepcopy(old["terminology"]), warnings)
    new["screening"]["read_decision"] = "pending"
    for score_key in ("relevance_score", "novelty_score", "method_quality_score", "priority_score"):
        if new["screening"].get(score_key) == 5 and not str(new["screening"].get("reason") or "").strip():
            new["screening"][score_key] = None
            warnings.append(f"reset default {score_key}=5 to null")
    new["figure_inventory"] = _figure_inventory(folder, md_path)
    new["provenance"].update({
        "generated_from": "mineru_markdown",
        "markdown_path": md_path.name,
        "metadata_path": metadata_path.name if metadata_path.exists() else "",
        "asset_manifest_path": asset_manifest_path.name if asset_manifest_path.exists() else "",
        "generated_at": now_iso(),
        "generator": "catalog_v3_0_to_v3_1_migration",
        "generator_version": "1.0",
        "input_markdown_md5": _file_md5(md_path),
        "input_metadata_md5": _file_md5(metadata_path),
        "generation_mode": "migration",
    })
    missing = _missing_fields(new)
    new["quality_control"] = {
        "catalog_completeness": "complete" if not missing else "partial",
        "missing_fields": missing,
        "warnings": sorted(set(warnings)),
        "is_test_fixture": False,
        "fallback_used": bool(missing),
    }
    report = {
        "catalog": str(catalog_path),
        "old_schema_version": old.get("schema_version"),
        "paper_number": paper_number,
        "paper_id": paper_id,
        "missing_fields": missing,
        "warnings": sorted(set(warnings)),
        "validation_errors_after_migration": validate_catalog_schema(new),
    }
    return new, report


def main() -> int:
    parser = argparse.ArgumentParser(description="ONE-SHOT migrate catalog v3.0 files to v3.1.")
    parser.add_argument("--paper-raw-dir", type=Path, default=PAPER_RAW_DIR)
    parser.add_argument("--papers-dir", type=Path, default=PAPERS_DIR)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--report", type=Path, default=None)
    args = parser.parse_args()

    write = args.apply and not args.dry_run
    items: list[dict[str, Any]] = []
    for root in (args.paper_raw_dir, args.papers_dir):
        for catalog_path in _catalog_paths(root):
            old = _read_json(catalog_path)
            if str(old.get("schema_version") or "") == "3.1":
                continue
            if str(old.get("schema_version") or "") != "3.0":
                items.append({"catalog": str(catalog_path), "status": "skipped", "reason": "not catalog v3.0"})
                continue
            new, report = migrate_catalog(catalog_path)
            report["status"] = "migrated" if write else "planned"
            items.append(report)
            if write:
                atomic_write_json(catalog_path, new, indent=2)

    payload = {
        "applied": write,
        "summary": {
            "planned_or_migrated": sum(1 for item in items if item.get("status") in {"planned", "migrated"}),
            "with_validation_errors": sum(1 for item in items if item.get("validation_errors_after_migration")),
            "skipped": sum(1 for item in items if item.get("status") == "skipped"),
        },
        "items": items,
    }
    if args.report:
        atomic_write_json(args.report, payload, indent=2)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
